# coding: utf-8

"""
    Codefresh API

    Codefresh API openAPI 3.0 specification  # noqa: E501

    OpenAPI spec version: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import codefresh_client
from codefresh_client.api.compositions_api import CompositionsApi  # noqa: E501
from codefresh_client.rest import ApiException


class TestCompositionsApi(unittest.TestCase):
    """CompositionsApi unit test stubs"""

    def setUp(self):
        self.api = codefresh_client.api.compositions_api.CompositionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_compositions_create(self):
        """Test case for compositions_create

        Create  # noqa: E501
        """
        pass

    def test_compositions_delete(self):
        """Test case for compositions_delete

        Delete  # noqa: E501
        """
        pass

    def test_compositions_duplicate(self):
        """Test case for compositions_duplicate

        Duplicate  # noqa: E501
        """
        pass

    def test_compositions_get(self):
        """Test case for compositions_get

        Get  # noqa: E501
        """
        pass

    def test_compositions_launch(self):
        """Test case for compositions_launch

        Launch  # noqa: E501
        """
        pass

    def test_compositions_list(self):
        """Test case for compositions_list

        List  # noqa: E501
        """
        pass

    def test_compositions_patch(self):
        """Test case for compositions_patch

        Patch  # noqa: E501
        """
        pass

    def test_compositions_update(self):
        """Test case for compositions_update

        Update  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
