# coding: utf-8

"""
    Codefresh API

    Codefresh API openAPI 3.0 specification  # noqa: E501

    OpenAPI spec version: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import codefresh_client
from codefresh_client.api.pipelines_api import PipelinesApi  # noqa: E501
from codefresh_client.rest import ApiException


class TestPipelinesApi(unittest.TestCase):
    """PipelinesApi unit test stubs"""

    def setUp(self):
        self.api = codefresh_client.api.pipelines_api.PipelinesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_pipelines_create(self):
        """Test case for pipelines_create

        Create  # noqa: E501
        """
        pass

    def test_pipelines_delete(self):
        """Test case for pipelines_delete

        Delete  # noqa: E501
        """
        pass

    def test_pipelines_get(self):
        """Test case for pipelines_get

        Get  # noqa: E501
        """
        pass

    def test_pipelines_list(self):
        """Test case for pipelines_list

        List  # noqa: E501
        """
        pass

    def test_pipelines_replace(self):
        """Test case for pipelines_replace

        Replace  # noqa: E501
        """
        pass

    def test_pipelines_run(self):
        """Test case for pipelines_run

        Run  # noqa: E501
        """
        pass

    def test_pipelines_validate_yaml(self):
        """Test case for pipelines_validate_yaml

        Validate yaml  # noqa: E501
        """
        pass

    def test_runtime_launch(self):
        """Test case for runtime_launch

        Launch  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
