# coding: utf-8

"""
    Codefresh API

    Codefresh API openAPI 3.0 specification  # noqa: E501

    OpenAPI spec version: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import codefresh_client
from codefresh_client.api.helm_repos_api import HelmReposApi  # noqa: E501
from codefresh_client.rest import ApiException


class TestHelmReposApi(unittest.TestCase):
    """HelmReposApi unit test stubs"""

    def setUp(self):
        self.api = codefresh_client.api.helm_repos_api.HelmReposApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_helm_repos_create(self):
        """Test case for helm_repos_create

        Create  # noqa: E501
        """
        pass

    def test_helm_repos_delete(self):
        """Test case for helm_repos_delete

        Delete  # noqa: E501
        """
        pass

    def test_helm_repos_get(self):
        """Test case for helm_repos_get

        Get  # noqa: E501
        """
        pass

    def test_helm_repos_list(self):
        """Test case for helm_repos_list

        List  # noqa: E501
        """
        pass

    def test_helm_repos_update(self):
        """Test case for helm_repos_update

        Update  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
