# coding: utf-8

"""
    Codefresh API

    Codefresh API openAPI 3.0 specification  # noqa: E501

    OpenAPI spec version: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import codefresh_client
from codefresh_client.api.environments_api import EnvironmentsApi  # noqa: E501
from codefresh_client.rest import ApiException


class TestEnvironmentsApi(unittest.TestCase):
    """EnvironmentsApi unit test stubs"""

    def setUp(self):
        self.api = codefresh_client.api.environments_api.EnvironmentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_envs_get(self):
        """Test case for envs_get

        Get  # noqa: E501
        """
        pass

    def test_envs_list(self):
        """Test case for envs_list

        List  # noqa: E501
        """
        pass

    def test_envs_pause(self):
        """Test case for envs_pause

        Pause  # noqa: E501
        """
        pass

    def test_envs_rename(self):
        """Test case for envs_rename

        Rename  # noqa: E501
        """
        pass

    def test_envs_start(self):
        """Test case for envs_start

        Start  # noqa: E501
        """
        pass

    def test_envs_status(self):
        """Test case for envs_status

        Status  # noqa: E501
        """
        pass

    def test_envs_stop(self):
        """Test case for envs_stop

        Stop  # noqa: E501
        """
        pass

    def test_envs_terminate(self):
        """Test case for envs_terminate

        Terminate  # noqa: E501
        """
        pass

    def test_envs_terminate_all(self):
        """Test case for envs_terminate_all

        Terminate all  # noqa: E501
        """
        pass

    def test_envs_unpause(self):
        """Test case for envs_unpause

        Unpause  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
