# coding: utf-8

"""
    Codefresh API

    Codefresh API openAPI 3.0 specification  # noqa: E501

    OpenAPI spec version: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import codefresh_client
from codefresh_client.api.accounts_api import AccountsApi  # noqa: E501
from codefresh_client.rest import ApiException


class TestAccountsApi(unittest.TestCase):
    """AccountsApi unit test stubs"""

    def setUp(self):
        self.api = codefresh_client.api.accounts_api.AccountsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_accounts_add_account(self):
        """Test case for accounts_add_account

        Add account  # noqa: E501
        """
        pass

    def test_accounts_add_existing_user_to_account(self):
        """Test case for accounts_add_existing_user_to_account

        Add existing user to account  # noqa: E501
        """
        pass

    def test_accounts_add_pending_user_without_account(self):
        """Test case for accounts_add_pending_user_without_account

        Add pending user without account  # noqa: E501
        """
        pass

    def test_accounts_add_user_to_account(self):
        """Test case for accounts_add_user_to_account

        Add user to account  # noqa: E501
        """
        pass

    def test_accounts_delete_account(self):
        """Test case for accounts_delete_account

        Delete account  # noqa: E501
        """
        pass

    def test_accounts_delete_admin(self):
        """Test case for accounts_delete_admin

        Delete admin  # noqa: E501
        """
        pass

    def test_accounts_delete_user_from_account(self):
        """Test case for accounts_delete_user_from_account

        Delete user from account  # noqa: E501
        """
        pass

    def test_accounts_get_by_id(self):
        """Test case for accounts_get_by_id

        Get by id  # noqa: E501
        """
        pass

    def test_accounts_get_users_for_account(self):
        """Test case for accounts_get_users_for_account

        Get users for account  # noqa: E501
        """
        pass

    def test_accounts_list_accounts(self):
        """Test case for accounts_list_accounts

        List accounts  # noqa: E501
        """
        pass

    def test_accounts_set_as_admin(self):
        """Test case for accounts_set_as_admin

        Set as admin  # noqa: E501
        """
        pass

    def test_accounts_update_account(self):
        """Test case for accounts_update_account

        Update account  # noqa: E501
        """
        pass

    def test_accounts_update_account_public_settings(self):
        """Test case for accounts_update_account_public_settings

        Update account public settings  # noqa: E501
        """
        pass

    def test_accounts_update_user_details(self):
        """Test case for accounts_update_user_details

        Update user details  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
