# coding: utf-8

"""
    Codefresh API

    Codefresh API openAPI 3.0 specification  # noqa: E501

    OpenAPI spec version: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import codefresh_client
from codefresh_client.models.runtimetestit_repo_data import RuntimetestitRepoData  # noqa: E501
from codefresh_client.rest import ApiException


class TestRuntimetestitRepoData(unittest.TestCase):
    """RuntimetestitRepoData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRuntimetestitRepoData(self):
        """Test RuntimetestitRepoData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = codefresh_client.models.runtimetestit_repo_data.RuntimetestitRepoData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
