# coding: utf-8

"""
    Codefresh API

    Codefresh API openAPI 3.0 specification  # noqa: E501

    OpenAPI spec version: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import codefresh_client
from codefresh_client.api.teams_api import TeamsApi  # noqa: E501
from codefresh_client.rest import ApiException


class TestTeamsApi(unittest.TestCase):
    """TeamsApi unit test stubs"""

    def setUp(self):
        self.api = codefresh_client.api.teams_api.TeamsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_teams_add_user(self):
        """Test case for teams_add_user

        Add user  # noqa: E501
        """
        pass

    def test_teams_create(self):
        """Test case for teams_create

        Create  # noqa: E501
        """
        pass

    def test_teams_list(self):
        """Test case for teams_list

        List  # noqa: E501
        """
        pass

    def test_teams_list_by_user(self):
        """Test case for teams_list_by_user

        List by user  # noqa: E501
        """
        pass

    def test_teams_remove_user(self):
        """Test case for teams_remove_user

        Remove user  # noqa: E501
        """
        pass

    def test_teams_synchronize_client_with_group(self):
        """Test case for teams_synchronize_client_with_group

        Synchronize client with group  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
