# coding: utf-8

"""
    Codefresh API

    Codefresh API openAPI 3.0 specification  # noqa: E501

    OpenAPI spec version: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import codefresh_client
from codefresh_client.api.features_api import FeaturesApi  # noqa: E501
from codefresh_client.rest import ApiException


class TestFeaturesApi(unittest.TestCase):
    """FeaturesApi unit test stubs"""

    def setUp(self):
        self.api = codefresh_client.api.features_api.FeaturesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_features_account(self):
        """Test case for features_account

        Account  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
