# coding: utf-8

"""
    Codefresh API

    Codefresh API openAPI 3.0 specification  # noqa: E501

    OpenAPI spec version: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import codefresh_client
from codefresh_client.api.tokens_api import TokensApi  # noqa: E501
from codefresh_client.rest import ApiException


class TestTokensApi(unittest.TestCase):
    """TokensApi unit test stubs"""

    def setUp(self):
        self.api = codefresh_client.api.tokens_api.TokensApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_tokens_delete(self):
        """Test case for tokens_delete

        Delete  # noqa: E501
        """
        pass

    def test_tokens_generate(self):
        """Test case for tokens_generate

        Generate  # noqa: E501
        """
        pass

    def test_tokens_list(self):
        """Test case for tokens_list

        List  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
