# coding: utf-8

"""
    Codefresh API

    Codefresh API openAPI 3.0 specification  # noqa: E501

    OpenAPI spec version: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import codefresh_client
from codefresh_client.api.triggers_api import TriggersApi  # noqa: E501
from codefresh_client.rest import ApiException


class TestTriggersApi(unittest.TestCase):
    """TriggersApi unit test stubs"""

    def setUp(self):
        self.api = codefresh_client.api.triggers_api.TriggersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_triggers_create(self):
        """Test case for triggers_create

        Create  # noqa: E501
        """
        pass

    def test_triggers_delete(self):
        """Test case for triggers_delete

        Delete  # noqa: E501
        """
        pass

    def test_triggers_get_event_triggers(self):
        """Test case for triggers_get_event_triggers

        Get event triggers  # noqa: E501
        """
        pass

    def test_triggers_get_pipeline_triggers(self):
        """Test case for triggers_get_pipeline_triggers

        Get pipeline triggers  # noqa: E501
        """
        pass

    def test_triggers_list(self):
        """Test case for triggers_list

        List  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
