# coding: utf-8

"""
    Codefresh API

    Codefresh API openAPI 3.0 specification  # noqa: E501

    OpenAPI spec version: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import codefresh_client
from codefresh_client.api.abac_api import AbacApi  # noqa: E501
from codefresh_client.rest import ApiException


class TestAbacApi(unittest.TestCase):
    """AbacApi unit test stubs"""

    def setUp(self):
        self.api = codefresh_client.api.abac_api.AbacApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_abac_list_by_resource(self):
        """Test case for abac_list_by_resource

        Get rules by resource  # noqa: E501
        """
        pass

    def test_abac_list_by_team(self):
        """Test case for abac_list_by_team

        Get rules by team id  # noqa: E501
        """
        pass

    def test_abac_rules_create(self):
        """Test case for abac_rules_create

        Create rule  # noqa: E501
        """
        pass

    def test_abac_rules_create_in_batch(self):
        """Test case for abac_rules_create_in_batch

        Create rules in batch  # noqa: E501
        """
        pass

    def test_abac_rules_create_or_delete(self):
        """Test case for abac_rules_create_or_delete

        Create or delete rules  # noqa: E501
        """
        pass

    def test_abac_rules_delete(self):
        """Test case for abac_rules_delete

        Delete rule  # noqa: E501
        """
        pass

    def test_abac_rules_get(self):
        """Test case for abac_rules_get

        Get rule  # noqa: E501
        """
        pass

    def test_abac_rules_list(self):
        """Test case for abac_rules_list

        List rules  # noqa: E501
        """
        pass

    def test_abac_rules_tags_create(self):
        """Test case for abac_rules_tags_create

        Create rules tags  # noqa: E501
        """
        pass

    def test_abac_rules_tags_update(self):
        """Test case for abac_rules_tags_update

        Update rule tags  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
