# coding: utf-8

"""
    Codefresh API

    Codefresh API openAPI 3.0 specification  # noqa: E501

    OpenAPI spec version: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import codefresh_client
from codefresh_client.models.inline_object24 import InlineObject24  # noqa: E501
from codefresh_client.rest import ApiException


class TestInlineObject24(unittest.TestCase):
    """InlineObject24 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineObject24(self):
        """Test InlineObject24"""
        # FIXME: construct object with mandatory attributes with example values
        # model = codefresh_client.models.inline_object24.InlineObject24()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
