# coding: utf-8

"""
    Codefresh API

    Codefresh API openAPI 3.0 specification  # noqa: E501

    OpenAPI spec version: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import codefresh_client
from codefresh_client.models.inline_object15 import InlineObject15  # noqa: E501
from codefresh_client.rest import ApiException


class TestInlineObject15(unittest.TestCase):
    """InlineObject15 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineObject15(self):
        """Test InlineObject15"""
        # FIXME: construct object with mandatory attributes with example values
        # model = codefresh_client.models.inline_object15.InlineObject15()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
