# coding: utf-8

"""
    Codefresh API

    Codefresh API openAPI 3.0 specification  # noqa: E501

    OpenAPI spec version: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import codefresh_client
from codefresh_client.models.inline_object31 import InlineObject31  # noqa: E501
from codefresh_client.rest import ApiException


class TestInlineObject31(unittest.TestCase):
    """InlineObject31 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineObject31(self):
        """Test InlineObject31"""
        # FIXME: construct object with mandatory attributes with example values
        # model = codefresh_client.models.inline_object31.InlineObject31()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
