# coding: utf-8

"""
    Codefresh API

    Codefresh API openAPI 3.0 specification  # noqa: E501

    OpenAPI spec version: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import codefresh_client
from codefresh_client.models.inline_object12 import InlineObject12  # noqa: E501
from codefresh_client.rest import ApiException


class TestInlineObject12(unittest.TestCase):
    """InlineObject12 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineObject12(self):
        """Test InlineObject12"""
        # FIXME: construct object with mandatory attributes with example values
        # model = codefresh_client.models.inline_object12.InlineObject12()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
