# coding: utf-8

"""
    Codefresh API

    Codefresh API openAPI 3.0 specification  # noqa: E501

    OpenAPI spec version: 0.0.2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from codefresh_client.api_client import ApiClient


class RuntimeEnvironmentsAccountApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def on_prem_runtime_envs_account_delete(self, runtime_environment_name, **kwargs):  # noqa: E501
        """Delete for account  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.on_prem_runtime_envs_account_delete(runtime_environment_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str runtime_environment_name: Runtime environment name (required)
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.on_prem_runtime_envs_account_delete_with_http_info(runtime_environment_name, **kwargs)  # noqa: E501
        else:
            (data) = self.on_prem_runtime_envs_account_delete_with_http_info(runtime_environment_name, **kwargs)  # noqa: E501
            return data

    def on_prem_runtime_envs_account_delete_with_http_info(self, runtime_environment_name, **kwargs):  # noqa: E501
        """Delete for account  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.on_prem_runtime_envs_account_delete_with_http_info(runtime_environment_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str runtime_environment_name: Runtime environment name (required)
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['runtime_environment_name']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method on_prem_runtime_envs_account_delete" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'runtime_environment_name' is set
        if ('runtime_environment_name' not in local_var_params or
                local_var_params['runtime_environment_name'] is None):
            raise ValueError("Missing the required parameter `runtime_environment_name` when calling `on_prem_runtime_envs_account_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'runtime_environment_name' in local_var_params:
            path_params['runtimeEnvironmentName'] = local_var_params['runtime_environment_name']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['apiKey']  # noqa: E501

        return self.api_client.call_api(
            '/admin/runtime-environments/account/modify/{runtimeEnvironmentName}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='object',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def on_prem_runtime_envs_account_list(self, account, **kwargs):  # noqa: E501
        """Get by account  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.on_prem_runtime_envs_account_list(account, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str account: Account (required)
        :param str limit: Limit
        :param str offset: Offset
        :param str account_ids: Account ids
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.on_prem_runtime_envs_account_list_with_http_info(account, **kwargs)  # noqa: E501
        else:
            (data) = self.on_prem_runtime_envs_account_list_with_http_info(account, **kwargs)  # noqa: E501
            return data

    def on_prem_runtime_envs_account_list_with_http_info(self, account, **kwargs):  # noqa: E501
        """Get by account  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.on_prem_runtime_envs_account_list_with_http_info(account, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str account: Account (required)
        :param str limit: Limit
        :param str offset: Offset
        :param str account_ids: Account ids
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['account', 'limit', 'offset', 'account_ids']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method on_prem_runtime_envs_account_list" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'account' is set
        if ('account' not in local_var_params or
                local_var_params['account'] is None):
            raise ValueError("Missing the required parameter `account` when calling `on_prem_runtime_envs_account_list`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'account' in local_var_params:
            path_params['account'] = local_var_params['account']  # noqa: E501

        query_params = []
        if 'limit' in local_var_params:
            query_params.append(('limit', local_var_params['limit']))  # noqa: E501
        if 'offset' in local_var_params:
            query_params.append(('offset', local_var_params['offset']))  # noqa: E501
        if 'account_ids' in local_var_params:
            query_params.append(('accountIds', local_var_params['account_ids']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['apiKey']  # noqa: E501

        return self.api_client.call_api(
            '/admin/runtime-environments/account/{account}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='object',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def on_prem_runtime_envs_account_modify(self, runtime_environment_name, **kwargs):  # noqa: E501
        """Add to account  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.on_prem_runtime_envs_account_modify(runtime_environment_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str runtime_environment_name: Runtime environment name (required)
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.on_prem_runtime_envs_account_modify_with_http_info(runtime_environment_name, **kwargs)  # noqa: E501
        else:
            (data) = self.on_prem_runtime_envs_account_modify_with_http_info(runtime_environment_name, **kwargs)  # noqa: E501
            return data

    def on_prem_runtime_envs_account_modify_with_http_info(self, runtime_environment_name, **kwargs):  # noqa: E501
        """Add to account  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.on_prem_runtime_envs_account_modify_with_http_info(runtime_environment_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str runtime_environment_name: Runtime environment name (required)
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['runtime_environment_name']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method on_prem_runtime_envs_account_modify" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'runtime_environment_name' is set
        if ('runtime_environment_name' not in local_var_params or
                local_var_params['runtime_environment_name'] is None):
            raise ValueError("Missing the required parameter `runtime_environment_name` when calling `on_prem_runtime_envs_account_modify`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'runtime_environment_name' in local_var_params:
            path_params['runtimeEnvironmentName'] = local_var_params['runtime_environment_name']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['apiKey']  # noqa: E501

        return self.api_client.call_api(
            '/admin/runtime-environments/account/modify/{runtimeEnvironmentName}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='object',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def on_prem_runtime_envs_account_set_default(self, account, runtime_environment_name, **kwargs):  # noqa: E501
        """Set default for account  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.on_prem_runtime_envs_account_set_default(account, runtime_environment_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str account: Account (required)
        :param str runtime_environment_name: Runtime environment name (required)
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.on_prem_runtime_envs_account_set_default_with_http_info(account, runtime_environment_name, **kwargs)  # noqa: E501
        else:
            (data) = self.on_prem_runtime_envs_account_set_default_with_http_info(account, runtime_environment_name, **kwargs)  # noqa: E501
            return data

    def on_prem_runtime_envs_account_set_default_with_http_info(self, account, runtime_environment_name, **kwargs):  # noqa: E501
        """Set default for account  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.on_prem_runtime_envs_account_set_default_with_http_info(account, runtime_environment_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str account: Account (required)
        :param str runtime_environment_name: Runtime environment name (required)
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['account', 'runtime_environment_name']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method on_prem_runtime_envs_account_set_default" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'account' is set
        if ('account' not in local_var_params or
                local_var_params['account'] is None):
            raise ValueError("Missing the required parameter `account` when calling `on_prem_runtime_envs_account_set_default`")  # noqa: E501
        # verify the required parameter 'runtime_environment_name' is set
        if ('runtime_environment_name' not in local_var_params or
                local_var_params['runtime_environment_name'] is None):
            raise ValueError("Missing the required parameter `runtime_environment_name` when calling `on_prem_runtime_envs_account_set_default`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'account' in local_var_params:
            path_params['account'] = local_var_params['account']  # noqa: E501
        if 'runtime_environment_name' in local_var_params:
            path_params['runtimeEnvironmentName'] = local_var_params['runtime_environment_name']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['apiKey']  # noqa: E501

        return self.api_client.call_api(
            '/admin/runtime-environments/account/default/{account}/{runtimeEnvironmentName}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='object',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)
