# coding: utf-8

"""
    Codefresh API

    Codefresh API openAPI 3.0 specification  # noqa: E501

    OpenAPI spec version: 0.0.2
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class InlineObject5(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'integrations': 'object',
        'notifications': 'list[AccountsaccountIdupdateNotifications]'
    }

    attribute_map = {
        'integrations': 'integrations',
        'notifications': 'notifications'
    }

    def __init__(self, integrations=None, notifications=None):  # noqa: E501
        """InlineObject5 - a model defined in OpenAPI"""  # noqa: E501

        self._integrations = None
        self._notifications = None
        self.discriminator = None

        if integrations is not None:
            self.integrations = integrations
        if notifications is not None:
            self.notifications = notifications

    @property
    def integrations(self):
        """Gets the integrations of this InlineObject5.  # noqa: E501


        :return: The integrations of this InlineObject5.  # noqa: E501
        :rtype: object
        """
        return self._integrations

    @integrations.setter
    def integrations(self, integrations):
        """Sets the integrations of this InlineObject5.


        :param integrations: The integrations of this InlineObject5.  # noqa: E501
        :type: object
        """

        self._integrations = integrations

    @property
    def notifications(self):
        """Gets the notifications of this InlineObject5.  # noqa: E501


        :return: The notifications of this InlineObject5.  # noqa: E501
        :rtype: list[AccountsaccountIdupdateNotifications]
        """
        return self._notifications

    @notifications.setter
    def notifications(self, notifications):
        """Sets the notifications of this InlineObject5.


        :param notifications: The notifications of this InlineObject5.  # noqa: E501
        :type: list[AccountsaccountIdupdateNotifications]
        """

        self._notifications = notifications

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineObject5):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
