# coding: utf-8

"""
    Codefresh API

    Codefresh API openAPI 3.0 specification  # noqa: E501

    OpenAPI spec version: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class InlineObject(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'tags': 'list[str]',
        'action': 'str',
        'resource': 'str',
        'team': 'str'
    }

    attribute_map = {
        'tags': 'tags',
        'action': 'action',
        'resource': 'resource',
        'team': 'team'
    }

    def __init__(self, tags=None, action=None, resource=None, team=None):  # noqa: E501
        """InlineObject - a model defined in OpenAPI"""  # noqa: E501

        self._tags = None
        self._action = None
        self._resource = None
        self._team = None
        self.discriminator = None

        if tags is not None:
            self.tags = tags
        if action is not None:
            self.action = action
        if resource is not None:
            self.resource = resource
        if team is not None:
            self.team = team

    @property
    def tags(self):
        """Gets the tags of this InlineObject.  # noqa: E501


        :return: The tags of this InlineObject.  # noqa: E501
        :rtype: list[str]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this InlineObject.


        :param tags: The tags of this InlineObject.  # noqa: E501
        :type: list[str]
        """

        self._tags = tags

    @property
    def action(self):
        """Gets the action of this InlineObject.  # noqa: E501


        :return: The action of this InlineObject.  # noqa: E501
        :rtype: str
        """
        return self._action

    @action.setter
    def action(self, action):
        """Sets the action of this InlineObject.


        :param action: The action of this InlineObject.  # noqa: E501
        :type: str
        """

        self._action = action

    @property
    def resource(self):
        """Gets the resource of this InlineObject.  # noqa: E501


        :return: The resource of this InlineObject.  # noqa: E501
        :rtype: str
        """
        return self._resource

    @resource.setter
    def resource(self, resource):
        """Sets the resource of this InlineObject.


        :param resource: The resource of this InlineObject.  # noqa: E501
        :type: str
        """

        self._resource = resource

    @property
    def team(self):
        """Gets the team of this InlineObject.  # noqa: E501


        :return: The team of this InlineObject.  # noqa: E501
        :rtype: str
        """
        return self._team

    @team.setter
    def team(self, team):
        """Sets the team of this InlineObject.


        :param team: The team of this InlineObject.  # noqa: E501
        :type: str
        """

        self._team = team

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineObject):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
