# coding: utf-8

"""
    Codefresh API

    Codefresh API openAPI 3.0 specification  # noqa: E501

    OpenAPI spec version: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class InlineResponse200(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'v': 'float',
        'id': 'str',
        'account_id': 'str',
        'filter': 'str',
        'name': 'str',
        'type': 'str'
    }

    attribute_map = {
        'v': '__v',
        'id': '_id',
        'account_id': 'accountId',
        'filter': 'filter',
        'name': 'name',
        'type': 'type'
    }

    def __init__(self, v=None, id=None, account_id=None, filter=None, name=None, type=None):  # noqa: E501
        """InlineResponse200 - a model defined in OpenAPI"""  # noqa: E501

        self._v = None
        self._id = None
        self._account_id = None
        self._filter = None
        self._name = None
        self._type = None
        self.discriminator = None

        if v is not None:
            self.v = v
        if id is not None:
            self.id = id
        if account_id is not None:
            self.account_id = account_id
        if filter is not None:
            self.filter = filter
        if name is not None:
            self.name = name
        if type is not None:
            self.type = type

    @property
    def v(self):
        """Gets the v of this InlineResponse200.  # noqa: E501


        :return: The v of this InlineResponse200.  # noqa: E501
        :rtype: float
        """
        return self._v

    @v.setter
    def v(self, v):
        """Sets the v of this InlineResponse200.


        :param v: The v of this InlineResponse200.  # noqa: E501
        :type: float
        """

        self._v = v

    @property
    def id(self):
        """Gets the id of this InlineResponse200.  # noqa: E501


        :return: The id of this InlineResponse200.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineResponse200.


        :param id: The id of this InlineResponse200.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def account_id(self):
        """Gets the account_id of this InlineResponse200.  # noqa: E501


        :return: The account_id of this InlineResponse200.  # noqa: E501
        :rtype: str
        """
        return self._account_id

    @account_id.setter
    def account_id(self, account_id):
        """Sets the account_id of this InlineResponse200.


        :param account_id: The account_id of this InlineResponse200.  # noqa: E501
        :type: str
        """

        self._account_id = account_id

    @property
    def filter(self):
        """Gets the filter of this InlineResponse200.  # noqa: E501


        :return: The filter of this InlineResponse200.  # noqa: E501
        :rtype: str
        """
        return self._filter

    @filter.setter
    def filter(self, filter):
        """Sets the filter of this InlineResponse200.


        :param filter: The filter of this InlineResponse200.  # noqa: E501
        :type: str
        """

        self._filter = filter

    @property
    def name(self):
        """Gets the name of this InlineResponse200.  # noqa: E501


        :return: The name of this InlineResponse200.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this InlineResponse200.


        :param name: The name of this InlineResponse200.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def type(self):
        """Gets the type of this InlineResponse200.  # noqa: E501


        :return: The type of this InlineResponse200.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this InlineResponse200.


        :param type: The type of this InlineResponse200.  # noqa: E501
        :type: str
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse200):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
